// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEEIURUW8HSXLIndKXK9M3zuML7RfS-RA',
    appId: '1:343087765656:web:22ad4086fed91f60ea58ed',
    messagingSenderId: '343087765656',
    projectId: 'air-sight',
    authDomain: 'air-sight.firebaseapp.com',
    storageBucket: 'air-sight.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNEBBLNnFihZcWESCLl-lk4UWgJt_4r3Q',
    appId: '1:343087765656:android:d31f0944d2bcafb6ea58ed',
    messagingSenderId: '343087765656',
    projectId: 'air-sight',
    storageBucket: 'air-sight.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf0zjsaPFzjUu-EPMujAfWkBDQyJAPh20',
    appId: '1:343087765656:ios:b55e623ee7e3beadea58ed',
    messagingSenderId: '343087765656',
    projectId: 'air-sight',
    storageBucket: 'air-sight.firebasestorage.app',
    iosBundleId: 'com.example.airSight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf0zjsaPFzjUu-EPMujAfWkBDQyJAPh20',
    appId: '1:343087765656:ios:b55e623ee7e3beadea58ed',
    messagingSenderId: '343087765656',
    projectId: 'air-sight',
    storageBucket: 'air-sight.firebasestorage.app',
    iosBundleId: 'com.example.airSight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEEIURUW8HSXLIndKXK9M3zuML7RfS-RA',
    appId: '1:343087765656:web:294c90896b6f2669ea58ed',
    messagingSenderId: '343087765656',
    projectId: 'air-sight',
    authDomain: 'air-sight.firebaseapp.com',
    storageBucket: 'air-sight.firebasestorage.app',
  );
}
