import 'package:flutter/material.dart';

import 'glossary_category.dart';
import 'glossary_word.dart';

const List<GlossaryCategory> glossaryCategories = [
  GlossaryCategory(name: 'Animals', icon: Icons.pets_rounded, color: Color(0xFF795548)),
  GlossaryCategory(name: 'Body', icon: Icons.accessibility_new_rounded, color: Color(0xFFFF5722)),
  GlossaryCategory(name: 'Classroom', icon: Icons.school_rounded, color: Color(0xFF4CAF50)),
  GlossaryCategory(name: 'Clothes', icon: Icons.checkroom_rounded, color: Color(0xFF607D8B)),
  GlossaryCategory(name: 'Colors', icon: Icons.palette_rounded, color: Color(0xFF9C27B0)),
  GlossaryCategory(name: 'Family', icon: Icons.family_restroom_rounded, color: Color(0xFFAB47BC)),
  GlossaryCategory(name: 'Food', icon: Icons.restaurant_rounded, color: Color(0xFFE91E63)),
  GlossaryCategory(name: 'Home', icon: Icons.home_rounded, color: Color(0xFFFF9800)),
  GlossaryCategory(name: 'Jobs', icon: Icons.work_rounded, color: Color(0xFF455A64)),
  GlossaryCategory(name: 'Kitchen', icon: Icons.kitchen_rounded, color: Color(0xFFFF7043)),
  GlossaryCategory(name: 'Nature', icon: Icons.park_rounded, color: Color(0xFF66BB6A)),
  GlossaryCategory(name: 'Numbers', icon: Icons.numbers_rounded, color: Color(0xFF2196F3)),
  GlossaryCategory(name: 'Objects', icon: Icons.category_rounded, color: Color(0xFF26A69A)),
  GlossaryCategory(name: 'People', icon: Icons.people_rounded, color: Color(0xFF3F51B5)),
  GlossaryCategory(name: 'Places', icon: Icons.location_city_rounded, color: Color(0xFF009688)),
  GlossaryCategory(name: 'School Actions', icon: Icons.edit_note_rounded, color: Color(0xFF7E57C2)),
  GlossaryCategory(name: 'Technology', icon: Icons.devices_rounded, color: Color(0xFF00ACC1)),
  GlossaryCategory(name: 'Time', icon: Icons.access_time_rounded, color: Color(0xFF5E35B1)),
  GlossaryCategory(name: 'Transport', icon: Icons.directions_bus_rounded, color: Color(0xFFFFB300)),
  GlossaryCategory(name: 'Weather', icon: Icons.wb_sunny_rounded, color: Color(0xFF29B6F6)),
];

const List<GlossaryWord> glossaryWords = [
  // Animals (1-12)
  GlossaryWord(id: '1', wordEn: 'bird', wordEs: 'pájaro', category: 'Animals', example: 'The bird is small.', exampleEs: 'El pájaro es pequeño.', aliases: ['bird', 'animal']),
  GlossaryWord(id: '2', wordEn: 'cat', wordEs: 'gato', category: 'Animals', example: 'The cat is sleeping.', exampleEs: 'El gato está durmiendo.', aliases: ['cat', 'feline', 'pet', 'animal']),
  GlossaryWord(id: '3', wordEn: 'cow', wordEs: 'vaca', category: 'Animals', example: 'The cow is big.', exampleEs: 'La vaca es grande.', aliases: ['cow', 'cattle', 'animal']),
  GlossaryWord(id: '4', wordEn: 'dog', wordEs: 'perro', category: 'Animals', example: 'The dog is friendly.', exampleEs: 'El perro es amigable.', aliases: ['dog', 'canine', 'puppy', 'pet', 'animal']),
  GlossaryWord(id: '5', wordEn: 'duck', wordEs: 'pato', category: 'Animals', example: 'The duck is in the water.', exampleEs: 'El pato está en el agua.', aliases: ['duck', 'bird', 'animal']),
  GlossaryWord(id: '6', wordEn: 'fish', wordEs: 'pez', category: 'Animals', example: 'The fish is blue.', exampleEs: 'El pez es azul.', aliases: ['fish', 'animal']),
  GlossaryWord(id: '7', wordEn: 'horse', wordEs: 'caballo', category: 'Animals', example: 'The horse runs fast.', exampleEs: 'El caballo corre rápido.', aliases: ['horse', 'animal']),
  GlossaryWord(id: '8', wordEn: 'lion', wordEs: 'león', category: 'Animals', example: 'The lion is strong.', exampleEs: 'El león es fuerte.', aliases: ['lion', 'animal']),
  GlossaryWord(id: '9', wordEn: 'mouse', wordEs: 'ratón', category: 'Animals', example: 'The mouse is small.', exampleEs: 'El ratón es pequeño.', aliases: ['mouse', 'rodent', 'animal']),
  GlossaryWord(id: '10', wordEn: 'pig', wordEs: 'cerdo', category: 'Animals', example: 'The pig is pink.', exampleEs: 'El cerdo es rosado.', aliases: ['pig', 'swine', 'animal']),
  GlossaryWord(id: '11', wordEn: 'rabbit', wordEs: 'conejo', category: 'Animals', example: 'The rabbit is white.', exampleEs: 'El conejo es blanco.', aliases: ['rabbit', 'bunny', 'animal']),
  GlossaryWord(id: '12', wordEn: 'turtle', wordEs: 'tortuga', category: 'Animals', example: 'The turtle is slow.', exampleEs: 'La tortuga es lenta.', aliases: ['turtle', 'tortoise', 'animal']),

  // Classroom (13-25)
  GlossaryWord(id: '13', wordEn: 'bag', wordEs: 'bolso', category: 'Classroom', example: 'My bag is on the chair.', exampleEs: 'Mi bolso está sobre la silla.', aliases: ['bag', 'handbag', 'tote bag']),
  GlossaryWord(id: '14', wordEn: 'board', wordEs: 'tablero', category: 'Classroom', example: 'The teacher writes on the board.', exampleEs: 'El profesor escribe en el tablero.', aliases: ['board', 'whiteboard', 'blackboard', 'chalkboard']),
  GlossaryWord(id: '15', wordEn: 'book', wordEs: 'libro', category: 'Classroom', example: 'I have a new book.', exampleEs: 'Tengo un libro nuevo.', aliases: ['book', 'textbook', 'publication', 'novel']),
  GlossaryWord(id: '16', wordEn: 'chair', wordEs: 'silla', category: 'Classroom', example: 'This is a chair.', exampleEs: 'Esta es una silla.', aliases: ['chair', 'seat', 'furniture', 'stool', 'armchair']),
  GlossaryWord(id: '17', wordEn: 'classroom', wordEs: 'salón de clase', category: 'Classroom', example: 'The classroom is clean.', exampleEs: 'El salón de clase está limpio.', aliases: ['classroom', 'room', 'class']),
  GlossaryWord(id: '18', wordEn: 'desk', wordEs: 'escritorio', category: 'Classroom', example: 'The desk is brown.', exampleEs: 'El escritorio es marrón.', aliases: ['desk', 'table', 'office desk']),
  GlossaryWord(id: '19', wordEn: 'eraser', wordEs: 'borrador', category: 'Classroom', example: 'The eraser is small.', exampleEs: 'El borrador es pequeño.', aliases: ['eraser', 'rubber']),
  GlossaryWord(id: '20', wordEn: 'marker', wordEs: 'marcador', category: 'Classroom', example: 'The marker is red.', exampleEs: 'El marcador es rojo.', aliases: ['marker', 'highlighter', 'pen']),
  GlossaryWord(id: '21', wordEn: 'notebook', wordEs: 'cuaderno', category: 'Classroom', example: 'My notebook is blue.', exampleEs: 'Mi cuaderno es azul.', aliases: ['notebook', 'notepad', 'book']),
  GlossaryWord(id: '22', wordEn: 'pen', wordEs: 'bolígrafo', category: 'Classroom', example: 'This is my pen.', exampleEs: 'Este es mi bolígrafo.', aliases: ['pen', 'ballpoint pen', 'stationery']),
  GlossaryWord(id: '23', wordEn: 'pencil', wordEs: 'lápiz', category: 'Classroom', example: 'The pencil is yellow.', exampleEs: 'El lápiz es amarillo.', aliases: ['pencil', 'stationery']),
  GlossaryWord(id: '24', wordEn: 'ruler', wordEs: 'regla', category: 'Classroom', example: 'The ruler is long.', exampleEs: 'La regla es larga.', aliases: ['ruler', 'measuring stick']),
  GlossaryWord(id: '25', wordEn: 'table', wordEs: 'mesa', category: 'Classroom', example: 'The book is on the table.', exampleEs: 'El libro está sobre la mesa.', aliases: ['table', 'dining table', 'desk', 'furniture']),

  // Home & Kitchen (26-39)
  GlossaryWord(id: '26', wordEn: 'bed', wordEs: 'cama', category: 'Home', example: 'The bed is comfortable.', exampleEs: 'La cama es cómoda.', aliases: ['bed', 'furniture', 'mattress']),
  GlossaryWord(id: '27', wordEn: 'bottle', wordEs: 'botella', category: 'Kitchen', example: 'The water bottle is on the table.', exampleEs: 'La botella de agua está sobre la mesa.', aliases: ['bottle', 'water bottle', 'drinkware', 'plastic bottle']),
  GlossaryWord(id: '28', wordEn: 'clock', wordEs: 'reloj de pared', category: 'Home', example: 'The clock is on the wall.', exampleEs: 'El reloj está en la pared.', aliases: ['clock', 'wall clock', 'analog clock', 'digital clock']),
  GlossaryWord(id: '29', wordEn: 'cup', wordEs: 'taza', category: 'Kitchen', example: 'I drink coffee from a cup.', exampleEs: 'Tomo café en una taza.', aliases: ['cup', 'coffee cup', 'mug', 'teacup', 'drinkware']),
  GlossaryWord(id: '30', wordEn: 'door', wordEs: 'puerta', category: 'Home', example: 'Please close the door.', exampleEs: 'Por favor cierra la puerta.', aliases: ['door', 'doorway']),
  GlossaryWord(id: '31', wordEn: 'fork', wordEs: 'tenedor', category: 'Kitchen', example: 'I eat with a fork.', exampleEs: 'Como con un tenedor.', aliases: ['fork', 'cutlery', 'utensil']),
  GlossaryWord(id: '32', wordEn: 'glass', wordEs: 'vaso', category: 'Kitchen', example: 'A glass of water.', exampleEs: 'Un vaso de agua.', aliases: ['glass', 'drinking glass', 'drinkware']),
  GlossaryWord(id: '33', wordEn: 'knife', wordEs: 'cuchillo', category: 'Kitchen', example: 'The knife is sharp.', exampleEs: 'El cuchillo está afilado.', aliases: ['knife', 'cutlery', 'kitchen knife', 'utensil']),
  GlossaryWord(id: '34', wordEn: 'lamp', wordEs: 'lámpara', category: 'Home', example: 'The lamp gives bright light.', exampleEs: 'La lámpara da luz brillante.', aliases: ['lamp', 'lighting', 'table lamp', 'light fixture']),
  GlossaryWord(id: '35', wordEn: 'mirror', wordEs: 'espejo', category: 'Home', example: 'Look in the mirror.', exampleEs: 'Mira en el espejo.', aliases: ['mirror']),
  GlossaryWord(id: '36', wordEn: 'plate', wordEs: 'plato', category: 'Kitchen', example: 'The food is on the plate.', exampleEs: 'La comida está en el plato.', aliases: ['plate', 'dish', 'tableware']),
  GlossaryWord(id: '37', wordEn: 'refrigerator', wordEs: 'nevera', category: 'Kitchen', example: 'The milk is in the refrigerator.', exampleEs: 'La leche está en la nevera.', aliases: ['refrigerator', 'fridge', 'appliance']),
  GlossaryWord(id: '38', wordEn: 'spoon', wordEs: 'cuchara', category: 'Kitchen', example: 'Eat the soup with a spoon.', exampleEs: 'Come la sopa con una cuchara.', aliases: ['spoon', 'cutlery', 'utensil']),
  GlossaryWord(id: '39', wordEn: 'window', wordEs: 'ventana', category: 'Home', example: 'Open the window, please.', exampleEs: 'Abre la ventana, por favor.', aliases: ['window']),

  // Technology (40-47)
  GlossaryWord(id: '40', wordEn: 'computer', wordEs: 'computador', category: 'Technology', example: 'I study on my computer.', exampleEs: 'Estudio en mi computador.', aliases: ['computer', 'desktop computer', 'pc', 'monitor']),
  GlossaryWord(id: '41', wordEn: 'headphones', wordEs: 'audífonos', category: 'Technology', example: 'I listen to music with headphones.', exampleEs: 'Escucho música con audífonos.', aliases: ['headphones', 'headset', 'earphones']),
  GlossaryWord(id: '42', wordEn: 'keyboard', wordEs: 'teclado', category: 'Technology', example: 'Type on the keyboard.', exampleEs: 'Escribe en el teclado.', aliases: ['keyboard', 'computer keyboard', 'input device']),
  GlossaryWord(id: '43', wordEn: 'laptop', wordEs: 'computador portátil', category: 'Technology', example: 'My laptop is fast.', exampleEs: 'Mi portátil es rápido.', aliases: ['laptop', 'notebook computer', 'computer']),
  GlossaryWord(id: '44', wordEn: 'mouse', wordEs: 'ratón de computador', category: 'Technology', example: 'Click with the mouse.', exampleEs: 'Haz clic con el ratón.', aliases: ['computer mouse', 'mouse']),
  GlossaryWord(id: '45', wordEn: 'phone', wordEs: 'teléfono', category: 'Technology', example: 'My phone is on the table.', exampleEs: 'Mi teléfono está sobre la mesa.', aliases: ['phone', 'mobile phone', 'cell phone', 'smartphone', 'telephone']),
  GlossaryWord(id: '46', wordEn: 'screen', wordEs: 'pantalla', category: 'Technology', example: 'The screen is large.', exampleEs: 'La pantalla es grande.', aliases: ['screen', 'display', 'monitor']),
  GlossaryWord(id: '47', wordEn: 'television', wordEs: 'televisor', category: 'Technology', example: 'Watch news on television.', exampleEs: 'Mira las noticias en el televisor.', aliases: ['television', 'tv', 'screen']),

  // Objects & Personal (48-57)
  GlossaryWord(id: '48', wordEn: 'backpack', wordEs: 'morral', category: 'Objects', example: 'The backpack is heavy.', exampleEs: 'El morral es pesado.', aliases: ['backpack', 'schoolbag', 'bag', 'luggage and bags']),
  GlossaryWord(id: '49', wordEn: 'box', wordEs: 'caja', category: 'Objects', example: 'The box is made of cardboard.', exampleEs: 'La caja es de cartón.', aliases: ['box', 'container', 'carton']),
  GlossaryWord(id: '50', wordEn: 'glasses', wordEs: 'gafas', category: 'Objects', example: 'He wears glasses to read.', exampleEs: 'Él usa gafas para leer.', aliases: ['glasses', 'eyewear', 'sunglasses', 'spectacles']),
  GlossaryWord(id: '51', wordEn: 'key', wordEs: 'llave', category: 'Objects', example: 'I have the house key.', exampleEs: 'Tengo la llave de la casa.', aliases: ['key', 'keys']),
  GlossaryWord(id: '52', wordEn: 'paper', wordEs: 'papel', category: 'Objects', example: 'Write on a sheet of paper.', exampleEs: 'Escribe en una hoja de papel.', aliases: ['paper', 'sheet of paper']),
  GlossaryWord(id: '53', wordEn: 'soap', wordEs: 'jabón', category: 'Objects', example: 'Wash your hands with soap.', exampleEs: 'Lava tus manos con jabón.', aliases: ['soap', 'bar of soap']),
  GlossaryWord(id: '54', wordEn: 'toothbrush', wordEs: 'cepillo de dientes', category: 'Objects', example: 'Use the toothbrush after eating.', exampleEs: 'Usa el cepillo de dientes después de comer.', aliases: ['toothbrush']),
  GlossaryWord(id: '55', wordEn: 'umbrella', wordEs: 'sombrilla', category: 'Objects', example: 'Take an umbrella for the rain.', exampleEs: 'Lleva una sombrilla para la lluvia.', aliases: ['umbrella']),
  GlossaryWord(id: '56', wordEn: 'wallet', wordEs: 'billetera', category: 'Objects', example: 'My money is in the wallet.', exampleEs: 'Mi dinero está en la billetera.', aliases: ['wallet', 'purse']),
  GlossaryWord(id: '57', wordEn: 'watch', wordEs: 'reloj de pulsera', category: 'Objects', example: 'Look at your watch.', exampleEs: 'Mira tu reloj.', aliases: ['watch', 'wrist watch']),

  // Food & Drinks (58-69)
  GlossaryWord(id: '58', wordEn: 'apple', wordEs: 'manzana', category: 'Food', example: 'The apple is red.', exampleEs: 'La manzana es roja.', aliases: ['apple', 'fruit']),
  GlossaryWord(id: '59', wordEn: 'banana', wordEs: 'banano', category: 'Food', example: 'The banana is sweet.', exampleEs: 'El banano es dulce.', aliases: ['banana', 'fruit']),
  GlossaryWord(id: '60', wordEn: 'bread', wordEs: 'pan', category: 'Food', example: 'Fresh bread smells good.', exampleEs: 'El pan fresco huele bien.', aliases: ['bread', 'baked goods', 'loaf']),
  GlossaryWord(id: '61', wordEn: 'cheese', wordEs: 'queso', category: 'Food', example: 'I like cheese on my sandwich.', exampleEs: 'Me gusta el queso en mi sándwich.', aliases: ['cheese', 'dairy']),
  GlossaryWord(id: '62', wordEn: 'coffee', wordEs: 'café', category: 'Food', example: 'A hot cup of coffee.', exampleEs: 'Una taza de café caliente.', aliases: ['coffee', 'coffee cup', 'drink']),
  GlossaryWord(id: '63', wordEn: 'egg', wordEs: 'huevo', category: 'Food', example: 'I eat an egg for breakfast.', exampleEs: 'Como un huevo al desayuno.', aliases: ['egg', 'food']),
  GlossaryWord(id: '64', wordEn: 'milk', wordEs: 'leche', category: 'Food', example: 'Cold milk in a glass.', exampleEs: 'Leche fría en un vaso.', aliases: ['milk', 'dairy', 'drink']),
  GlossaryWord(id: '65', wordEn: 'orange', wordEs: 'naranja', category: 'Food', example: 'An orange is juicy.', exampleEs: 'Una naranja es jugosa.', aliases: ['orange', 'citrus', 'fruit']),
  GlossaryWord(id: '66', wordEn: 'pizza', wordEs: 'pizza', category: 'Food', example: 'Pizza with tomato and cheese.', exampleEs: 'Pizza con tomate y queso.', aliases: ['pizza', 'fast food']),
  GlossaryWord(id: '67', wordEn: 'sandwich', wordEs: 'sándwich', category: 'Food', example: 'A ham and cheese sandwich.', exampleEs: 'Un sándwich de jamón y queso.', aliases: ['sandwich', 'fast food', 'snack']),
  GlossaryWord(id: '68', wordEn: 'tea', wordEs: 'té', category: 'Food', example: 'Green tea is good.', exampleEs: 'El té verde es bueno.', aliases: ['tea', 'drink']),
  GlossaryWord(id: '69', wordEn: 'water', wordEs: 'agua', category: 'Food', example: 'Drink plenty of water.', exampleEs: 'Bebe suficiente agua.', aliases: ['water', 'drink']),

  // Clothes (70-79)
  GlossaryWord(id: '70', wordEn: 'coat', wordEs: 'abrigo', category: 'Clothes', example: 'Wear a warm coat.', exampleEs: 'Usa un abrigo abrigado.', aliases: ['coat', 'outerwear', 'clothing']),
  GlossaryWord(id: '71', wordEn: 'dress', wordEs: 'vestido', category: 'Clothes', example: 'She wears a pretty dress.', exampleEs: 'Ella usa un vestido bonito.', aliases: ['dress', 'clothing']),
  GlossaryWord(id: '72', wordEn: 'hat', wordEs: 'sombrero', category: 'Clothes', example: 'A sun hat protects your head.', exampleEs: 'Un sombrero de sol protege tu cabeza.', aliases: ['hat', 'cap', 'headwear']),
  GlossaryWord(id: '73', wordEn: 'jacket', wordEs: 'chaqueta', category: 'Clothes', example: 'Zip up your jacket.', exampleEs: 'Sube la cremallera de tu chaqueta.', aliases: ['jacket', 'outerwear', 'clothing']),
  GlossaryWord(id: '74', wordEn: 'pants', wordEs: 'pantalones', category: 'Clothes', example: 'Blue jeans and black pants.', exampleEs: 'Jeans azules y pantalones negros.', aliases: ['pants', 'trousers', 'jeans', 'clothing']),
  GlossaryWord(id: '75', wordEn: 'shirt', wordEs: 'camisa', category: 'Clothes', example: 'A white dress shirt.', exampleEs: 'Una camisa blanca de vestir.', aliases: ['shirt', 'dress shirt', 'clothing']),
  GlossaryWord(id: '76', wordEn: 'shoes', wordEs: 'zapatos', category: 'Clothes', example: 'New running shoes.', exampleEs: 'Zapatos nuevos para correr.', aliases: ['shoes', 'shoe', 'footwear', 'sneakers']),
  GlossaryWord(id: '77', wordEn: 'skirt', wordEs: 'falda', category: 'Clothes', example: 'A long pleated skirt.', exampleEs: 'Una falda larga plisada.', aliases: ['skirt', 'clothing']),
  GlossaryWord(id: '78', wordEn: 'socks', wordEs: 'medias', category: 'Clothes', example: 'Warm cotton socks.', exampleEs: 'Medias abrigadas de algodón.', aliases: ['socks', 'footwear']),
  GlossaryWord(id: '79', wordEn: 't-shirt', wordEs: 'camiseta', category: 'Clothes', example: 'A cotton t-shirt.', exampleEs: 'Una camiseta de algodón.', aliases: ['t-shirt', 'tshirt', 'shirt', 'clothing']),

  // Colors (80-87)
  GlossaryWord(id: '80', wordEn: 'black', wordEs: 'negro', category: 'Colors', example: 'The cat is black.', exampleEs: 'El gato es negro.', aliases: ['black']),
  GlossaryWord(id: '81', wordEn: 'blue', wordEs: 'azul', category: 'Colors', example: 'The sky is blue.', exampleEs: 'El cielo es azul.', aliases: ['blue']),
  GlossaryWord(id: '82', wordEn: 'green', wordEs: 'verde', category: 'Colors', example: 'The grass is green.', exampleEs: 'El pasto es verde.', aliases: ['green']),
  GlossaryWord(id: '83', wordEn: 'orange', wordEs: 'naranja', category: 'Colors', example: 'The basketball is orange.', exampleEs: 'El balón de baloncesto es naranja.', aliases: ['orange']),
  GlossaryWord(id: '84', wordEn: 'purple', wordEs: 'morado', category: 'Colors', example: 'Grapes are purple.', exampleEs: 'Las uvas son moradas.', aliases: ['purple']),
  GlossaryWord(id: '85', wordEn: 'red', wordEs: 'rojo', category: 'Colors', example: 'The apple is red.', exampleEs: 'La manzana es roja.', aliases: ['red']),
  GlossaryWord(id: '86', wordEn: 'white', wordEs: 'blanco', category: 'Colors', example: 'Snow is white.', exampleEs: 'La nieve es blanca.', aliases: ['white']),
  GlossaryWord(id: '87', wordEn: 'yellow', wordEs: 'amarillo', category: 'Colors', example: 'The sun is yellow.', exampleEs: 'El sol es amarillo.', aliases: ['yellow']),

  // Numbers (88-94)
  GlossaryWord(id: '88', wordEn: 'one', wordEs: 'uno', category: 'Numbers', example: 'I have one sister.', exampleEs: 'Tengo una hermana.', aliases: ['one', '1']),
  GlossaryWord(id: '89', wordEn: 'two', wordEs: 'dos', category: 'Numbers', example: 'Two eyes to see.', exampleEs: 'Dos ojos para ver.', aliases: ['two', '2']),
  GlossaryWord(id: '90', wordEn: 'three', wordEs: 'tres', category: 'Numbers', example: 'Three meals a day.', exampleEs: 'Tres comidas al día.', aliases: ['three', '3']),
  GlossaryWord(id: '91', wordEn: 'four', wordEs: 'cuatro', category: 'Numbers', example: 'A table has four legs.', exampleEs: 'Una mesa tiene cuatro patas.', aliases: ['four', '4']),
  GlossaryWord(id: '92', wordEn: 'five', wordEs: 'cinco', category: 'Numbers', example: 'Five fingers on a hand.', exampleEs: 'Cinco dedos en una mano.', aliases: ['five', '5']),
  GlossaryWord(id: '93', wordEn: 'ten', wordEs: 'diez', category: 'Numbers', example: 'I count from one to ten.', exampleEs: 'Cuento del uno al diez.', aliases: ['ten', '10']),
  GlossaryWord(id: '94', wordEn: 'twenty', wordEs: 'veinte', category: 'Numbers', example: 'There are twenty students.', exampleEs: 'Hay veinte estudiantes.', aliases: ['twenty', '20']),

  // Body (95-102)
  GlossaryWord(id: '95', wordEn: 'arm', wordEs: 'brazo', category: 'Body', example: 'Raise your right arm.', exampleEs: 'Levanta tu brazo derecho.', aliases: ['arm']),
  GlossaryWord(id: '96', wordEn: 'ear', wordEs: 'oreja', category: 'Body', example: 'Listen with your ear.', exampleEs: 'Escucha con tu oreja.', aliases: ['ear']),
  GlossaryWord(id: '97', wordEn: 'eye', wordEs: 'ojo', category: 'Body', example: 'Close your left eye.', exampleEs: 'Cierra tu ojo izquierdo.', aliases: ['eye']),
  GlossaryWord(id: '98', wordEn: 'foot', wordEs: 'pie', category: 'Body', example: 'Put your shoes on your foot.', exampleEs: 'Pon los zapatos en tu pie.', aliases: ['foot', 'feet']),
  GlossaryWord(id: '99', wordEn: 'hand', wordEs: 'mano', category: 'Body', example: 'Wave your hand.', exampleEs: 'Mueve tu mano.', aliases: ['hand']),
  GlossaryWord(id: '100', wordEn: 'head', wordEs: 'cabeza', category: 'Body', example: 'Nod your head yes.', exampleEs: 'Asiente con la cabeza que sí.', aliases: ['head']),
  GlossaryWord(id: '101', wordEn: 'mouth', wordEs: 'boca', category: 'Body', example: 'Open your mouth to speak.', exampleEs: 'Abre la boca para hablar.', aliases: ['mouth']),
  GlossaryWord(id: '102', wordEn: 'nose', wordEs: 'nariz', category: 'Body', example: 'Smell flowers with your nose.', exampleEs: 'Huele flores con tu nariz.', aliases: ['nose']),
];